### ISSUE TITLE
国内网络demo地址可以访问么

### ISSUE THREAD

**Issue by shuanglong520** [zwssunny/easychatgpt#2]
我配置完apiKey
返回内容失败，原因是failed to connect to api.openai.com/108.160.165.173 (port 443) from /172.21.107.2 (port 57274) after 60000ms

**Comment by zwssunny** [comment]
不行，需要科学上网

**Comment by shuanglong520** [comment]
本地开启科学上网了，模拟器好像也访问不了外网，连接失败
我用电脑发射的wifi也不行
必须手机也得科学上网呗

**Comment by zwssunny** [comment]
模拟器我没试过。手机科学上网，和通过代理网关可以链接

**Comment by shuanglong520** [comment]
谢谢，手机科学上网，demo正常
